server:
  host: "http://localhost"
  port: 8080


nats:
  ConnString: "nats://nats:4222"

logger:
  level: "info"
  encoding: "json"
  path: "sample-log.log"

database:
  host: "localhost"
  user: "postgres"
  pass: "postgres"
  port: 5432
  name: "my_db"
