version: "3.8"

services:
  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - app_network
    volumes:
      - redis_data:/data

  nats:
    image: nats:latest
    container_name: nats
    ports:
      - "4222:4222"
      - "8222:8222"
    networks:
      - app_network

  server:
    build:
      context: .
      dockerfile: ./deployments/server.Dockerfile
    container_name: server
    environment:
      - DB_HOST=postgres
      - DB_USER=postgres
      - DB_PASS=postgres
      - DB_PORT=5432
      - DB_NAME=my_db
      - DB_SSLMODE=disable
    depends_on:
      postgres:
        condition: service_healthy
      nats:
        condition: service_started
    networks:
      - app_network
    ports:
      - "8080:8080"

  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: my_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 2s
      timeout: 5s
      retries: 10
    networks:
      - app_network


volumes:
  postgres_data:
  redis_data:

networks:
  app_network:
