server:
  host: localhost
  port: 8080


nats:
  ConnString: "localhost:4222"

logger:
  level: "info"
  encoding: "json"
  path: "../test-log.log"

redis:
  host: "localhost:6379"
  password: ""
  db: 0

database:
  host: "localhost"
  user: "postgres"
  pass: "postgres"
  port: 5432
  name: "test_db"
